### ISSUE TITLE
Name of the package is different from the repo name

### ISSUE THREAD

**Issue by pulyaevskiy** [VenChat/sqljocky2#1]
Maybe it would be less confusing and search-friendly to have the same everywhere?
To be consistent with the original package I'd suggest `sqljocky2` (not `sqljockEy`).
This would require only renaming this repository, package name looks good in `pubspec.yaml`.

**Comment by FaisalAbid** [comment]
Ah good point. I will rename the repo

**Comment by pulyaevskiy** [comment]
Awesome, thanks!
